@echo off
setlocal DisableDelayedExpansion
:: PC Cleanup v2 -- Source-repo launcher
::
:: You are looking at the SOURCE CODE (GitHub "Code > Download ZIP" or a git clone).
:: The ready-to-run script is dist\pccleanup.ps1, which is generated by
:: build\Build.ps1 and is deliberately NOT checked into git. This launcher
:: builds it from src\ and then runs it.
::
:: Customize config\*.json -- that is the source copy. dist\config\ is build
:: output and is overwritten every time this launcher runs.
::
:: Just want to use the tool? Download the release ZIP instead:
::   https://github.com/bradley1320/pc-cleanup/releases

cd /d "%~dp0"
if errorlevel 1 goto :cdfailed
if not exist "build\Build.ps1" goto :nobuild

echo Building dist\pccleanup.ps1 from source...
powershell -NoLogo -NoProfile -ExecutionPolicy Bypass -File "build\Build.ps1"
if not "%errorlevel%"=="0" goto :builderror
if not exist "dist\pccleanup.ps1" goto :buildmissing

echo.
powershell -NoLogo -NoProfile -ExecutionPolicy Bypass -File "dist\pccleanup.ps1" %*
set "rc=%errorlevel%"
pause
exit /b %rc%

:cdfailed
echo.
echo   [x] Could not switch to the folder containing this launcher
echo       Why: The path may be on a disconnected network drive, or blocked
echo            by permissions.
echo       Fix: Copy the folder to a local drive (for example your Desktop)
echo            and run it again.
echo.
pause
exit /b 1

:nobuild
echo.
echo   [x] Could not find build\Build.ps1
echo       Why: This folder is not a complete copy of the repository, so the
echo            tool cannot be built from source here.
echo       Fix: Download the release ZIP (it includes the compiled script):
echo            https://github.com/bradley1320/pc-cleanup/releases
echo            Unblock it, extract it, then run the Run.bat inside it.
echo.
pause
exit /b 1

:builderror
echo.
echo   [x] Build failed -- build\Build.ps1 reported an error
echo       Why: See the build output above for the specific failure. A
echo            partly-built dist\pccleanup.ps1 may exist but is not usable.
echo       Fix: Download the release ZIP (it includes the compiled script):
echo            https://github.com/bradley1320/pc-cleanup/releases
echo.
pause
exit /b 1

:buildmissing
echo.
echo   [x] Build finished but dist\pccleanup.ps1 was not produced
echo       Why: The build reported success yet wrote no output file. The
echo            src\ folder may be incomplete.
echo       Fix: Download the release ZIP (it includes the compiled script):
echo            https://github.com/bradley1320/pc-cleanup/releases
echo.
pause
exit /b 1
